const jwtDecode = require("jwt-decode");
const SockJS = require("sockjs-client");
const { Client } = require("@stomp/stompjs");
import "./background/particles.min";
import "./authrules.js";
import "./regrules.js";
import "./mainchat_logic.js";
import "./mainchat_chatlist_logic.js";
import "./mainchat_adminpanel.js";
import "./mainchat_invitechat.js";
