const jwtDecode = require("jwt-decode");
const SockJS = require("sockjs-client");
const { Client } = require("@stomp/stompjs");
import "./background/particles.min";
import "./background/app";
import "./authrules.js";
import "./regrules.js";
import "./mainchatlogic.js";
import "./mainchat_li_logic.js";
import "./mainchat_adminpanel.js";
